spring:
  application:
    name: SpringSecurityJWT
  datasource:
    url: jdbc:mysql://localhost:3306/tailor?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Avdevs@123
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
      show-sql: true
    open-in-view: true
logging:
  level:
    org.springframework.security: TRACE

cache:
  size: 100000

springdoc:
  swagger-ui:
    layout: "BaseLayout"
    path: "/api-docs"
    disable-swagger-default-url: true
